language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999
matrix:
  allow_failures:
  - julia: nightly
script:
  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("ImagePhaseCongruency"); Pkg.test("ImagePhaseCongruency"; coverage=true)'
